### 전국 미세먼지 농도 데이터프레임 생성

In [ ]:
import os
os.getcwd()

In [ ]:
import pandas as pd
import numpy as np
dust = pd.read_excel("./mini_data/dust.xlsx")

In [ ]:
dust

In [ ]:
dust_do = dust[dust['구분(2)'] == '도평균'].copy()

In [ ]:
dust_do

In [ ]:
dust_do['구분(1)'] = ['경기도','강원도','충청북도','충청남도','전라북도','전라남도','경상북도','경상남도','제주특별자치도']

In [ ]:
dust_do.reset_index(inplace=True,drop=True)

In [ ]:
dust_do.drop(columns=['구분(2)'],inplace=True)

In [ ]:
dust = dust[dust['구분(1)'].notnull()].iloc[:9,:]

In [ ]:
dust.drop(columns=['구분(2)'],inplace=True)

In [ ]:
dust = pd.concat([dust,dust_do],ignore_index=True)

In [ ]:
dust.set_index("구분(1)",inplace=True)

In [ ]:
dust = dust.applymap(lambda x: x.replace("*", "") if isinstance(x, str) else x)

In [ ]:
dust = dust.astype(int)

In [ ]:
dust

### [미세먼지 + 환자] 데이터프레임 전부 int형 전처리

In [1]:
import pickle
with open("./data/result_dust_sick.pkl","rb") as f:
    res = pickle.load(f)

In [2]:
df = res

In [3]:
df = df.applymap(lambda x : x.replace(',','') if type(x) == str else x)

In [4]:
res = df.set_index("날짜").astype(int).reset_index()

In [5]:
res

,날짜,전국 먼지 농도,환자수 합계,서울 먼지 농도,서울 환자수,부산 먼지 농도,부산 환자수,대구 먼지 농도,대구 환자수,인천 먼지 농도,...,전북 먼지 농도,전북 환자수,전남 먼지 농도,전남 환자수,경북 먼지 농도,경북 환자수,경남 먼지 농도,경남 환자수,제주 먼지 농도,제주 환자수
0,2019.10,32,8420041,31,1651751,27,549988,27,388517,35,...,34,301130,27,275841,31,384469,30,531581,32,117507
1,2019.11,41,8876775,40,1727085,35,601619,41,423010,41,...,43,313391,35,299858,40,419228,37,584199,40,122846
2,2019.12,39,10114677,42,1964570,35,684773,42,484563,40,...,36,362909,28,339472,39,486458,33,674959,29,140324
3,2020.01,39,9905347,42,1907110,32,669359,37,482232,42,...,40,365627,31,359138,34,495040,29,657986,31,139180
4,2020.02,38,6293450,41,1190445,34,438312,38,312377,37,...,36,240867,31,245238,35,332637,32,451946,34,94353
5,2020.03,40,3924177,45,770076,33,260568,38,164963,41,...,41,162072,31,160778,36,178757,31,254970,35,62404
6,2020.04,41,3214874,44,613213,36,206569,39,143364,39,...,41,138937,34,132105,38,150203,33,203819,41,60524
7,2020.05,34,3774056,35,724624,32,219152,38,141004,31,...,34,152485,29,143670,33,154626,32,230141,36,62497
8,2020.06,34,3716173,36,666557,27,255212,35,153099,32,...,36,148443,26,138221,32,172829,29,244963,27,57878
9,2020.07,20,3537495,21,634526,18,236044,22,172278,21,...,18,145974,17,136593,18,176975,20,226054,20,63143
10,2020.08,24,3046704,23,561718,31,197854,25,143849,24,...,22,128113,28,110458,23,148290,29,195921,29,56138
11,2020.09,22,3869242,19,701555,24,234574,25,193475,20,...,23,159808,22,138467,22,198327,24,252197,26,57857
12,2020.10,34,4356416,33,735050,30,271761,33,229439,34,...,35,181480,28,166360,31,219291,29,304816,31,68745
13,2020.11,38,4921929,42,847274,31,317483,40,235751,39,...,36,197328,29,180065,36,241617,30,338904,28,75053
14,2020.12,38,3725686,42,639403,33,246785,38,199415,39,...,36,151866,28,141484,36,201194,30,249753,24,68526
15,2021.01,39,2682386,38,484092,36,178011,40,133667,37,...,40,110028,34,116548,38,133301,33,178380,31,40987
16,2021.02,43,2738737,48,482881,37,187805,41,133295,46,...,42,113748,35,114486,40,134938,33,189559,34,50234
17,2021.03,65,4144187,67,739601,60,278621,59,199533,69,...,75,156267,64,147002,56,194742,53,269182,72,64683
18,2021.04,41,4786581,42,895335,37,292809,42,259459,42,...,43,166348,34,166627,42,233574,34,291981,36,68691
19,2021.05,52,3996212,61,736703,36,250241,41,197542,59,...,56,145204,46,130532,43,192001,36,243753,42,58472
20,2021.06,32,3554168,33,641100,26,225028,35,164514,36,...,36,143023,27,116733,31,172453,27,228129,25,50453
21,2021.07,22,2895654,24,527742,18,186769,19,138641,29,...,20,117043,19,110789,21,146120,20,189069,19,48155
22,2021.08,21,2628365,22,488460,19,173103,21,135163,22,...,20,105220,20,89481,23,133817,20,161188,17,44315
23,2021.09,17,3915467,15,685117,17,246711,18,196045,16,...,18,150052,17,136300,18,184513,17,251192,20,45539
24,2021.10,27,4726771,27,793596,23,324029,26,235812,28,...,31,184720,24,165888,25,236483,23,329615,24,79483

In [6]:
with open("./dataframe.pkl","wb") as f:
    pickle.dump(res,f)

### DataFrame Visualization

In [ ]:
res.head()

In [ ]:
from matplotlib import rc
rc('font', family='AppleGothic')

#### Using matplotlib

In [ ]:
import matplotlib.pyplot as plt

## 데이터 가져오기

stock_df1 = res
# stock_df2 = web.DataReader('GOOG','yahoo',start,end).reset_index()

## 꺾은선 그래프 그리기
fig, ax1 = plt.subplots(figsize=(20, 5))

ax2 = ax1.twinx()
lns1 = ax1.plot(stock_df1['날짜'], stock_df1['전국 먼지 농도'], label='전국 먼지 농도', color='red')
lns2 = ax2.plot(stock_df1['날짜'], stock_df1['환자수 합계'], label='호흡기 환자수', color='blue')
lns = lns1 + lns2
labs = [l.get_label() for l in lns]
ax1.legend(lns, labs, loc=0)

ax1.grid()
ax1.set_xlabel("date")
ax1.set_ylabel("전국 먼지 농도")
ax2.set_ylabel("호흡기 환자수")
plt.show()

#### Using Pyecharts (미완성)

In [ ]:
import pickle

with open("./age.pkl","rb") as f:
    df = pickle.load(f)

In [ ]:
df.reset_index(drop=True,inplace=True)

In [ ]:
df

In [ ]:
young = pd.concat([df.iloc[4:6,:],df.iloc[14:16,:]]).groupby(['나이']).sum()

#1. 20대 + 30대 값을 구한다.
#2. 위 공식에 넣는다.
young.loc['청년_총계'] = young.sum().values

In [ ]:
young

In [ ]:
old = pd.concat([df.iloc[8:10,:],df.iloc[18:20,:]]).groupby(['나이']).sum()
old.loc['노년_총계'] = old.sum()
old

### 청년 그래프

In [ ]:
from pyecharts.charts import Bar
from pyecharts import options as opts
from sklearn.preprocessing import MinMaxScaler

# Create the first bar chart object
bar_chart1 = Bar()
bar_chart1.add_xaxis(list(res.날짜))
dust_data = list(res['전국 먼지 농도'])
dust_scaler = MinMaxScaler()
dust_normalized = np.around(dust_scaler.fit_transform(np.array(dust_data).reshape(-1, 1)).flatten(), decimals=2)
bar_chart1.add_yaxis('전국 먼지 농도', list(dust_normalized))

# Create the second bar chart object
bar_chart2 = Bar()
bar_chart2.add_xaxis(list(res['전국 먼지 농도']))
patient_data = list(young.loc['청년_총계'].values)
patient_scaler = MinMaxScaler()
patient_normalized = np.around(patient_scaler.fit_transform(np.array(patient_data).reshape(-1, 1)).flatten(), decimals=2)
bar_chart2.add_yaxis('청년 호흡기 환자수', list(patient_normalized))

# Combine the two bar charts into a single chart object
combo_chart = bar_chart1.overlap(bar_chart2)

# Set the title and other options for the chart
combo_chart.set_global_opts(title_opts=opts.TitleOpts(title="청년층 날짜별 미세먼지/호흡기 환자 수 분포"),
                            xaxis_opts=opts.AxisOpts(name="날짜"),
                            yaxis_opts=opts.AxisOpts(name="미세먼지 농도/ 환자 수"))

# Render the chart to an HTML file
combo_chart.render("young_dust_sick.html")

In [ ]:
from pyecharts.charts import Bar
from pyecharts import options as opts
from sklearn.preprocessing import MinMaxScaler
# Create the first bar chart object
bar_chart1 = Bar()
bar_chart1.add_xaxis(list(res.날짜))
dust_data = list(res['전국 먼지 농도'])
dust_scaler = MinMaxScaler()
dust_normalized = np.around(dust_scaler.fit_transform(np.array(dust_data).reshape(-1, 1)).flatten(), decimals=2)
bar_chart1.add_yaxis('전국 먼지 농도', list(dust_normalized))

# Create the second bar chart object
bar_chart2 = Bar()
bar_chart2.add_xaxis(list(res['전국 먼지 농도']))
patient_data = list(old.loc['노년_총계'].values)
patient_scaler = MinMaxScaler()
patient_normalized = np.around(patient_scaler.fit_transform(np.array(patient_data).reshape(-1, 1)).flatten(), decimals=2)
bar_chart2.add_yaxis('노년 호흡기 환자수', list(patient_normalized))

# Combine the two bar charts into a single chart object
combo_chart = bar_chart1.overlap(bar_chart2)

# Set the title and other options for the chart
combo_chart.set_global_opts(title_opts=opts.TitleOpts(title="노년층 날짜별 미세먼지/호흡기 환자 수 분포"),
                            xaxis_opts=opts.AxisOpts(name="날짜"),
                            yaxis_opts=opts.AxisOpts(name="미세먼지 농도/ 환자 수"))

# Render the chart to an HTML file
combo_chart.render("old_dust_sick.html")